import { Inject, Injectable } from '@angular/core';
import { Platform } from '@ionic/angular';
@Injectable({
  providedIn: 'root',
})
export class SharedVariablesService {
  globalVariables: any = {};

  apiUrl: any = {};

  verifyCode : any;
  verificationID : any

  constructor() {
    this.globalVariables.projectID = 'autoneda';

    this.globalVariables.appName = 'AutoNeda';

    this.globalVariables.NotificationTitle = 'AutoNeda';

    this.globalVariables.SMSTitle = 'AutoNeda';

    this.globalVariables.IOSAppID = '';

    this.globalVariables.defaultLatitude = 21.51;
    this.globalVariables.defaultLongitude = 39.1;

    this.globalVariables.baseURL = 'https://api.fixeny.com';

    this.globalVariables.appDefaultLang = 'ar';

    this.globalVariables.http_config = {
      mobileauthorization:
        'AWe~?N1zq]CE(5y!XM@]6IqH6.%R`xLsN~JKH$T/sY8PuNJRtH:s?@@7Ea',
    };

    this.globalVariables.pushNotificationsOptions = {
      android: {
        senderID: '662245175296',
        alert: 'true',
        badge: 'true',
        sound: 'true',
      },
      ios: {
        senderID: '662245175296',
        alert: 'true',
        badge: 'true',
        sound: 'true',
      },
      windows: {},
    };

    this.globalVariables.countries_names = {
      bd: 'bangladesh',
      be: 'belgium',
      bf: 'burkina faso',
      bg: 'bulgaria',
      ba: 'bosnia and herzegovina',
      bb: 'barbados',
      wf: 'wallis and futuna',
      bl: 'saint barthelemy',
      bm: 'bermuda',
      bn: 'brunei',
      bo: 'bolivia',
      bh: 'bahrain',
      bi: 'burundi',
      bj: 'benin',
      bt: 'bhutan',
      jm: 'jamaica',
      bv: 'bouvet island',
      bw: 'botswana',
      ws: 'samoa',
      bq: 'bonaire, saint eustatius and saba ',
      br: 'brazil',
      bs: 'bahamas',
      je: 'jersey',
      by: 'belarus',
      bz: 'belize',
      ru: 'russia',
      rw: 'rwanda',
      rs: 'serbia',
      tl: 'east timor',
      re: 'reunion',
      tm: 'turkmenistan',
      tj: 'tajikistan',
      ro: 'romania',
      tk: 'tokelau',
      gw: 'guinea-bissau',
      gu: 'guam',
      gt: 'guatemala',
      gs: 'south georgia and the south sandwich islands',
      gr: 'greece',
      gq: 'equatorial guinea',
      gp: 'guadeloupe',
      jp: 'japan',
      gy: 'guyana',
      gg: 'guernsey',
      gf: 'french guiana',
      ge: 'georgia',
      gd: 'grenada',
      gb: 'united kingdom',
      ga: 'gabon',
      sv: 'el salvador',
      gn: 'guinea',
      gm: 'gambia',
      gl: 'greenland',
      gi: 'gibraltar',
      gh: 'ghana',
      om: 'oman',
      tn: 'tunisia',
      jo: 'jordan',
      hr: 'croatia',
      ht: 'haiti',
      hu: 'hungary',
      hk: 'hong kong',
      hn: 'honduras',
      hm: 'heard island and mcdonald islands',
      ve: 'venezuela',
      pr: 'puerto rico',
      ps: 'palestinian territory',
      pw: 'palau',
      pt: 'portugal',
      sj: 'svalbard and jan mayen',
      py: 'paraguay',
      iq: 'iraq',
      pa: 'panama',
      pf: 'french polynesia',
      pg: 'papua new guinea',
      pe: 'peru',
      pk: 'pakistan',
      ph: 'philippines',
      pn: 'pitcairn',
      pl: 'poland',
      pm: 'saint pierre and miquelon',
      zm: 'zambia',
      eh: 'western sahara',
      ee: 'estonia',
      eg: 'egypt',
      za: 'south africa',
      ec: 'ecuador',
      it: 'italy',
      vn: 'vietnam',
      sb: 'solomon islands',
      et: 'ethiopia',
      so: 'somalia',
      zw: 'zimbabwe',
      sa: 'saudi arabia',
      es: 'spain',
      er: 'eritrea',
      me: 'montenegro',
      md: 'moldova',
      mg: 'madagascar',
      mf: 'saint martin',
      ma: 'morocco',
      mc: 'monaco',
      uz: 'uzbekistan',
      mm: 'myanmar',
      ml: 'mali',
      mo: 'macao',
      mn: 'mongolia',
      mh: 'marshall islands',
      mk: 'macedonia',
      mu: 'mauritius',
      mt: 'malta',
      mw: 'malawi',
      mv: 'maldives',
      mq: 'martinique',
      mp: 'northern mariana islands',
      ms: 'montserrat',
      mr: 'mauritania',
      im: 'isle of man',
      ug: 'uganda',
      tz: 'tanzania',
      my: 'malaysia',
      mx: 'mexico',
      il: 'israel',
      fr: 'france',
      io: 'british indian ocean territory',
      sh: 'saint helena',
      fi: 'finland',
      fj: 'fiji',
      fk: 'falkland islands',
      fm: 'micronesia',
      fo: 'faroe islands',
      ni: 'nicaragua',
      nl: 'netherlands',
      no: 'norway',
      na: 'namibia',
      vu: 'vanuatu',
      nc: 'new caledonia',
      ne: 'niger',
      nf: 'norfolk island',
      ng: 'nigeria',
      nz: 'new zealand',
      np: 'nepal',
      nr: 'nauru',
      nu: 'niue',
      ck: 'cook islands',
      xk: 'kosovo',
      ci: 'ivory coast',
      ch: 'switzerland',
      co: 'colombia',
      cn: 'china',
      cm: 'cameroon',
      cl: 'chile',
      cc: 'cocos islands',
      ca: 'canada',
      cg: 'republic of the congo',
      cf: 'central african republic',
      cd: 'democratic republic of the congo',
      cz: 'czech republic',
      cy: 'cyprus',
      cx: 'christmas island',
      cr: 'costa rica',
      cw: 'curacao',
      cv: 'cape verde',
      cu: 'cuba',
      sz: 'swaziland',
      sy: 'syria',
      sx: 'sint maarten',
      kg: 'kyrgyzstan',
      ke: 'kenya',
      ss: 'south sudan',
      sr: 'suriname',
      ki: 'kiribati',
      kh: 'cambodia',
      kn: 'saint kitts and nevis',
      km: 'comoros',
      st: 'sao tome and principe',
      sk: 'slovakia',
      kr: 'south korea',
      si: 'slovenia',
      kp: 'north korea',
      kw: 'kuwait',
      sn: 'senegal',
      sm: 'san marino',
      sl: 'sierra leone',
      sc: 'seychelles',
      kz: 'kazakhstan',
      ky: 'cayman islands',
      sg: 'singapore',
      se: 'sweden',
      sd: 'sudan',
      do: 'dominican republic',
      dm: 'dominica',
      dj: 'djibouti',
      dk: 'denmark',
      vg: 'british virgin islands',
      de: 'germany',
      ye: 'yemen',
      dz: 'algeria',
      us: 'united states',
      uy: 'uruguay',
      yt: 'mayotte',
      um: 'united states minor outlying islands',
      lb: 'lebanon',
      lc: 'saint lucia',
      la: 'laos',
      tv: 'tuvalu',
      tw: 'taiwan',
      tt: 'trinidad and tobago',
      tr: 'turkey',
      lk: 'sri lanka',
      li: 'liechtenstein',
      lv: 'latvia',
      to: 'tonga',
      lt: 'lithuania',
      lu: 'luxembourg',
      lr: 'liberia',
      ls: 'lesotho',
      th: 'thailand',
      tf: 'french southern territories',
      tg: 'togo',
      td: 'chad',
      tc: 'turks and caicos islands',
      ly: 'libya',
      va: 'vatican',
      vc: 'saint vincent and the grenadines',
      ae: 'united arab emirates',
      ad: 'andorra',
      ag: 'antigua and barbuda',
      af: 'afghanistan',
      ai: 'anguilla',
      vi: 'u.s. virgin islands',
      is: 'iceland',
      ir: 'iran',
      am: 'armenia',
      al: 'albania',
      ao: 'angola',
      aq: 'antarctica',
      as: 'american samoa',
      ar: 'argentina',
      au: 'australia',
      at: 'austria',
      aw: 'aruba',
      in: 'india',
      ax: 'aland islands',
      az: 'azerbaijan',
      ie: 'ireland',
      id: 'indonesia',
      ua: 'ukraine',
      qa: 'qatar',
      mz: 'mozambique',
    };
    this.globalVariables.countries_codes = {
      bd: '880',
      be: '32',
      bf: '226',
      bg: '359',
      ba: '387',
      bb: '+1-246',
      wf: '681',
      bl: '590',
      bm: '+1-441',
      bn: '673',
      bo: '591',
      bh: '973',
      bi: '257',
      bj: '229',
      bt: '975',
      jm: '+1-876',
      bv: '',
      bw: '267',
      ws: '685',
      bq: '599',
      br: '55',
      bs: '+1-242',
      je: '+44-1534',
      by: '375',
      bz: '501',
      ru: '7',
      rw: '250',
      rs: '381',
      tl: '670',
      re: '262',
      tm: '993',
      tj: '992',
      ro: '40',
      tk: '690',
      gw: '245',
      gu: '+1-671',
      gt: '502',
      gs: '',
      gr: '30',
      gq: '240',
      gp: '590',
      jp: '81',
      gy: '592',
      gg: '+44-1481',
      gf: '594',
      ge: '995',
      gd: '+1-473',
      gb: '44',
      ga: '241',
      sv: '503',
      gn: '224',
      gm: '220',
      gl: '299',
      gi: '350',
      gh: '233',
      om: '968',
      tn: '216',
      jo: '962',
      hr: '385',
      ht: '509',
      hu: '36',
      hk: '852',
      hn: '504',
      hm: ' ',
      ve: '58',
      pr: '+1-787 and 1-939',
      ps: '970',
      pw: '680',
      pt: '351',
      sj: '47',
      py: '595',
      iq: '964',
      pa: '507',
      pf: '689',
      pg: '675',
      pe: '51',
      pk: '92',
      ph: '63',
      pn: '870',
      pl: '48',
      pm: '508',
      zm: '260',
      eh: '212',
      ee: '372',
      eg: '20',
      za: '27',
      ec: '593',
      it: '39',
      vn: '84',
      sb: '677',
      et: '251',
      so: '252',
      zw: '263',
      sa: '966',
      es: '34',
      er: '291',
      me: '382',
      md: '373',
      mg: '261',
      mf: '590',
      ma: '212',
      mc: '377',
      uz: '998',
      mm: '95',
      ml: '223',
      mo: '853',
      mn: '976',
      mh: '692',
      mk: '389',
      mu: '230',
      mt: '356',
      mw: '265',
      mv: '960',
      mq: '596',
      mp: '+1-670',
      ms: '+1-664',
      mr: '222',
      im: '+44-1624',
      ug: '256',
      tz: '255',
      my: '60',
      mx: '52',
      il: '972',
      fr: '33',
      io: '246',
      sh: '290',
      fi: '358',
      fj: '679',
      fk: '500',
      fm: '691',
      fo: '298',
      ni: '505',
      nl: '31',
      no: '47',
      na: '264',
      vu: '678',
      nc: '687',
      ne: '227',
      nf: '672',
      ng: '234',
      nz: '64',
      np: '977',
      nr: '674',
      nu: '683',
      ck: '682',
      xk: '',
      ci: '225',
      ch: '41',
      co: '57',
      cn: '86',
      cm: '237',
      cl: '56',
      cc: '61',
      ca: '1',
      cg: '242',
      cf: '236',
      cd: '243',
      cz: '420',
      cy: '357',
      cx: '61',
      cr: '506',
      cw: '599',
      cv: '238',
      cu: '53',
      sz: '268',
      sy: '963',
      sx: '599',
      kg: '996',
      ke: '254',
      ss: '211',
      sr: '597',
      ki: '686',
      kh: '855',
      kn: '+1-869',
      km: '269',
      st: '239',
      sk: '421',
      kr: '82',
      si: '386',
      kp: '850',
      kw: '965',
      sn: '221',
      sm: '378',
      sl: '232',
      sc: '248',
      kz: '7',
      ky: '+1-345',
      sg: '65',
      se: '46',
      sd: '249',
      do: '+1-809 and 1-829',
      dm: '+1-767',
      dj: '253',
      dk: '45',
      vg: '+1-284',
      de: '49',
      ye: '967',
      dz: '213',
      us: '1',
      uy: '598',
      yt: '262',
      um: '1',
      lb: '961',
      lc: '+1-758',
      la: '856',
      tv: '688',
      tw: '886',
      tt: '+1-868',
      tr: '90',
      lk: '94',
      li: '423',
      lv: '371',
      to: '676',
      lt: '370',
      lu: '352',
      lr: '231',
      ls: '266',
      th: '66',
      tf: '',
      tg: '228',
      td: '235',
      tc: '+1-649',
      ly: '218',
      va: '379',
      vc: '+1-784',
      ae: '971',
      ad: '376',
      ag: '+1-268',
      af: '93',
      ai: '+1-264',
      vi: '+1-340',
      is: '354',
      ir: '98',
      am: '374',
      al: '355',
      ao: '244',
      aq: '',
      as: '+1-684',
      ar: '54',
      au: '61',
      at: '43',
      aw: '297',
      in: '91',
      ax: '+358-18',
      az: '994',
      ie: '353',
      id: '62',
      ua: '380',
      qa: '974',
      mz: '258',
    };

    this.apiUrl.usersRegistration = this.globalVariables.baseURL + '/api/login';
    this.apiUrl.verification =
      this.globalVariables.baseURL + '/api/verification';
    this.apiUrl.initApp = this.globalVariables.baseURL + '/api/init_app';
    this.apiUrl.getAttr = this.globalVariables.baseURL + '/api/attr';
    this.apiUrl.logout = this.globalVariables.baseURL + '/api/logout';
    this.apiUrl.contactUs = this.globalVariables.baseURL + '/api/contactus';
    this.apiUrl.registerGCMToken =
      this.globalVariables.baseURL + '/api/gcm_register';
    this.apiUrl.customerProfile =
      this.globalVariables.baseURL + '/api/customers/profile';
    this.apiUrl.customerProfileUpdate =
      this.globalVariables.baseURL + '/api/customers/profile_update';
    this.apiUrl.initState =
      this.globalVariables.baseURL + '/api/autoneda/state';
    this.apiUrl.callStudent =
      this.globalVariables.baseURL + '/api/autoneda/call_student';
    this.apiUrl.registerPayment =
      this.globalVariables.baseURL + '/api/autoneda/register_payment';
    this.apiUrl.ContactWhatsapp = 'https://api.whatsapp.com/send?phone=';
    this.apiUrl.helpImage =
      'https://i.letsw.com/img/cloud/autoneda/help_image.png';
    this.apiUrl.noSchoolsImage =
      'https://i.letsw.com/img/cloud/autoneda/no_school.png';
    this.apiUrl.registerPaymentImage =
      'https://i.letsw.com/img/cloud/autoneda/register.png';

      this.apiUrl.upSert = this.globalVariables.baseURL + '/api/upsert';
      this.apiUrl.delete = this.globalVariables.baseURL + '/api/delete'
  }

  
}
